### ISSUE TITLE
feature - Customize the configuration file location and use a simpler configuration format (not YAML)

### ISSUE THREAD

**Issue by medz** [medz/prisma-dart#15]
Add a runtime configuration file, which is added to git ignore, and moves to other directories with the program's compiled binaries.

E.g: `.prismarc`:
```
DATABASE_URL = postgres://seven@localhost:5432/demo?schema=public
```

Add configuration items in `pubspec.yaml` to specify the path of the runtime configuration file (compared to the location of `pubspec.yaml`):
```yaml
prisma:
  prismarc: .prismarc # Prisma runtime configuration, and dotenv can be selected or set together
  dotenv: .env # Prisma runtime load dotenv file, and prismarc can be selected or set together
  schame: prisma/schema.prisma # Custom Prisma schema file path
```

Find runtime configuration order:

- step 1: Read the prisma runtime configuration file path in pubspec.yaml, if it is not configured or can't find `pubspec.yaml`, it will pop up. **Note**: It is relatively easy to find the `pubspec.yaml` file, just read it directly from the current running directory.
- step 2: Read the `.prismarc` configuration file from the current working directory, and exit if the file does not exist
- step 3: Read a `.prismarc` file from the current script directory
- step 4: Merge environment variables
