### ISSUE TITLE
Type errors may occur when using it in a dart_frog project and how to fix 

### ISSUE THREAD

**Issue by NeroSong** [medz/prisma-dart#325]
Ran into the same problem as #324 ,  a lot of following type errors after running `npx prisma generate`.

``` dart
The argument type 'dynamic' can't be assigned to the parameter type 'Map<dynamic, dynamic>'.

```

Updating to `v4.0.0-beta.1` didn't fix it however.

After checking, I found it's the default  `very_good_analysis` in `dev_dependencies` that caused the problem. 

Add an exclusion in `analysis_options.yaml` can fix it.

```yaml
include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - build/**
    - prisma/**  # add this line
linter:
  rules:
    file_names: false
```

Hope this helps someone who is experiencing the same problem :)
